# Generated by Django 3.2.5 on 2022-07-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookfreeclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=100)),
                ('contactNumber', models.IntegerField(default='')),
                ('whatsappNumber', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='contactform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=100)),
                ('contactNumber', models.IntegerField(default='')),
                ('whatsappNumber', models.IntegerField(default='')),
                ('query', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='featuredCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='', upload_to='attachments/')),
                ('oldprice', models.IntegerField(default='')),
                ('newprice', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='feedbackform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('classes', models.CharField(default='', max_length=100)),
                ('contactNumber', models.IntegerField(default='')),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='popularCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='', upload_to='attachments/')),
                ('oldprice', models.IntegerField(default='')),
                ('newprice', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='', upload_to='attachments/')),
            ],
        ),
    ]
