# Generated by Django 4.0.6 on 2022-08-11 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expogradeacademy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredcourse',
            name='newprice',
        ),
        migrations.RemoveField(
            model_name='featuredcourse',
            name='oldprice',
        ),
        migrations.RemoveField(
            model_name='popularcourse',
            name='newprice',
        ),
        migrations.RemoveField(
            model_name='popularcourse',
            name='oldprice',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='image',
        ),
    ]
